"""initial

Revision ID: e56a46be8006
Revises: 
Create Date: 2026-09-04 03:45:01.679611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e56a46be8006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone', sa.Enum('source', 'master', 'publish', name='assetzone'), nullable=False),
    sa.Column('status', sa.Enum('topic', 'drafting', 'finalized', 'publishing', 'published', name='assetstatus'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('object_key', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('source_path', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_index('ix_assets_text_trgm', 'assets', ['text_content'], unique=False, postgresql_using='gin', postgresql_ops={'text_content': 'gin_trgm_ops'})
    op.create_index('ix_assets_title_trgm', 'assets', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('derivations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_asset_id', sa.UUID(), nullable=False),
    sa.Column('derived_asset_id', sa.UUID(), nullable=False),
    sa.Column('recipe_ref', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['derived_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'derived_asset_id', name='uq_derivation_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derivations')
    op.drop_index('ix_assets_title_trgm', table_name='assets', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_assets_text_trgm', table_name='assets', postgresql_using='gin', postgresql_ops={'text_content': 'gin_trgm_ops'})
    op.drop_table('assets')
    # ### end Alembic commands ###
    sa.Enum(name="assetzone").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="assetstatus").drop(op.get_bind(), checkfirst=True)
