/**
 * CDD 语义图标注册表
 *
 * 统一应用的图标导入入口。使用语义化命名，屏蔽底层图标库细节。
 * 新代码推荐从此导入，旧代码不受影响。
 *
 * @example
 *   import { Icons } from '@/components/ui/icons'
 *   <Button><Icons.Add size={16} />新建</Button>
 *   <Icons.Delete size={16} className="text-destructive" />
 *
 * 命名规范：
 *   - 语义优先：Icons.Save 而非 FloppyDisk
 *   - 动作命名：Icons.Add / Delete / Edit / Close / Search
 *   - 对象命名：Icons.Vehicle / Calendar / Document
 */

import {
  // ===== 操作类 =====
  Plus,
  PlusCircle,
  Trash,
  FloppyDisk,
  PencilSimple,
  X,
  MagnifyingGlass,
  DownloadSimple,
  UploadSimple,
  ArrowCounterClockwise,
  ClockCounterClockwise,
  CopySimple,
  ShareNetwork,
  DotsThree,
  FunnelSimple,
  SlidersHorizontal,
  Sliders,
  Export,
  SignOut,
  Play,
  Pause,
  SkipForward,
  PaperPlaneRight,
  ListBullets,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretDoubleLeft,
  CaretDoubleRight,

  // ===== 状态类 =====
  Check,
  CheckCircle,
  XCircle,
  WarningCircle,
  WarningOctagon,
  Info,
  Prohibit,
  SealCheck,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Question,

  // ===== 文件/文档类 =====
  FileText,
  FileXls,
  FilePdf,
  Image,
  Paperclip,

  // ===== 业务对象类 =====
  Car,
  Wrench,
  User,
  UserPlus,
  UserCheck,
  UserMinus,
  Users,
  Calendar,
  Clock,
  MapPin,
  CurrencyDollar,
  Money,
  CreditCard,
  Package,
  Tag,
  Ticket,
  Receipt,
  Gift,
  Star,
  Heart,
  Bell,
  Certificate,
  Bookmark,
  Clipboard,
  ClipboardText,
  ShoppingCart,
  Wallet,
  Buildings,
  House,
  Phone,
  Envelope,
  Globe,
  Briefcase,
  Database,
  HardDrive,
  Headphones,
  Storefront,
  BookOpen,
  Gauge,
  Pulse,
  Crosshair,
  Lightbulb,
  Signature,
  SquaresFour,
  ChatCircle,
  FolderOpen,
  Circle,

  // ===== 图表/数据类 =====
  ChartBar,
  ChartLine,
  ChartPie,
  TrendUp,
  Percent,

  // ===== UI 控件类 =====
  Eye,
  EyeSlash,
  Sun,
  Moon,
  GearSix,
  Printer,
  SpinnerGap,
  LockKey,
} from '@phosphor-icons/react'

/** CDD 语义图标注册表 */
export const Icons = {
  // ---- 操作 ----
  Add: Plus,
  AddCircle: PlusCircle,
  Delete: Trash,
  Save: FloppyDisk,
  Edit: PencilSimple,
  Close: X,
  Search: MagnifyingGlass,
  Download: DownloadSimple,
  Upload: UploadSimple,
  Refresh: ArrowCounterClockwise,
  History: ClockCounterClockwise,
  Copy: CopySimple,
  Share: ShareNetwork,
  More: DotsThree,
  Filter: FunnelSimple,
  Sort: SlidersHorizontal,
  Adjust: Sliders,
  Export,
  Logout: SignOut,
  Play,
  Pause,
  Skip: SkipForward,
  Send: PaperPlaneRight,
  List: ListBullets,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronDown: CaretDown,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  ChevronUp: CaretUp,
  FirstPage: CaretDoubleLeft,
  LastPage: CaretDoubleRight,

  // ---- 状态 ----
  Check,
  Success: CheckCircle,
  Error: XCircle,
  Warning: WarningCircle,
  AlertOctagon: WarningOctagon,
  Info,
  Block: Prohibit,
  Verified: SealCheck,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Help: Question,

  // ---- 文件 ----
  Document: FileText,
  Spreadsheet: FileXls,
  Pdf: FilePdf,
  Image,
  Attachment: Paperclip,

  // ---- 业务对象 ----
  Vehicle: Car,
  Repair: Wrench,
  User,
  UserAdd: UserPlus,
  UserCheck,
  UserRemove: UserMinus,
  Users,
  Calendar,
  Time: Clock,
  Location: MapPin,
  Currency: CurrencyDollar,
  Cash: Money,
  Payment: CreditCard,
  Package,
  Tag,
  Ticket,
  Receipt,
  Gift,
  Star,
  Heart,
  Notification: Bell,
  Certificate,
  Bookmark,
  Clipboard,
  Report: ClipboardText,
  Cart: ShoppingCart,
  Wallet,
  Store: Buildings,
  Home: House,
  Phone,
  Email: Envelope,
  Website: Globe,
  Briefcase,
  Database,
  HardDrive,
  Headphones,
  Storefront,
  Book: BookOpen,
  Gauge,
  Pulse,
  Target: Crosshair,
  Idea: Lightbulb,
  Signature,
  Grid: SquaresFour,
  Chat: ChatCircle,
  FolderOpen,
  Circle,

  // ---- 图表 ----
  Chart: ChartBar,
  ChartLine,
  ChartPie,
  Trending: TrendUp,
  Percentage: Percent,

  // ---- UI ----
  Eye,
  EyeOff: EyeSlash,
  LightMode: Sun,
  DarkMode: Moon,
  Settings: GearSix,
  Print: Printer,
  Loading: SpinnerGap,
  Password: LockKey,
} as const

/** 图标名称类型 */
export type IconName = keyof typeof Icons
